export const FakeData = [
    {
        id: 1,
        appName: 'Portie',
        address: '314 Kim Pass',
        bed: 4,
        bath: 2,
        price: 685,
        ImgMain: 'http://dummyimage.com/236x129.png/5fa2dd/ffffff',
        shortSummary:
            'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
        serviceCharge: 6185,
        sequrityDeposit: 4,
        flatSize: 4357,
        Img1: 'http://dummyimage.com/208x143.png/ff4444/ffffff',
        Img2: 'http://dummyimage.com/150x156.png/cc0000/ffffff',
        img3: 'http://dummyimage.com/163x150.png/5fa2dd/ffffff',
        img4: 'http://dummyimage.com/223x194.png/cc0000/ffffff',
    },
    {
        id: 2,
        appName: 'Anselm',
        address: '457 Twin Pines Court',
        bed: 4,
        bath: 2,
        price: 583,
        ImgMain: 'http://dummyimage.com/127x212.png/dddddd/000000',
        shortSummary:
            'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
        serviceCharge: 6866,
        sequrityDeposit: 2,
        flatSize: 2817,
        Img1: 'http://dummyimage.com/117x218.png/dddddd/000000',
        Img2: 'http://dummyimage.com/107x206.png/ff4444/ffffff',
        img3: 'http://dummyimage.com/148x108.png/5fa2dd/ffffff',
        img4: 'http://dummyimage.com/247x177.png/ff4444/ffffff',
    },
    {
        id: 3,
        appName: 'Dalia',
        address: '6 Union Avenue',
        bed: 5,
        bath: 3,
        price: 606,
        ImgMain: 'http://dummyimage.com/128x128.png/cc0000/ffffff',
        shortSummary:
            'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.',
        serviceCharge: 3523,
        sequrityDeposit: 4,
        flatSize: 3079,
        Img1: 'http://dummyimage.com/141x117.png/cc0000/ffffff',
        Img2: 'http://dummyimage.com/154x140.png/cc0000/ffffff',
        img3: 'http://dummyimage.com/127x177.png/cc0000/ffffff',
        img4: 'http://dummyimage.com/194x193.png/dddddd/000000',
    },
    {
        id: 4,
        appName: 'Nahum',
        address: '2 Golf Course Parkway',
        bed: 4,
        bath: 3,
        price: 656,
        ImgMain: 'http://dummyimage.com/238x231.png/5fa2dd/ffffff',
        shortSummary:
            'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
        serviceCharge: 6557,
        sequrityDeposit: 5,
        flatSize: 4633,
        Img1: 'http://dummyimage.com/138x235.png/5fa2dd/ffffff',
        Img2: 'http://dummyimage.com/228x246.png/dddddd/000000',
        img3: 'http://dummyimage.com/228x197.png/ff4444/ffffff',
        img4: 'http://dummyimage.com/213x216.png/5fa2dd/ffffff',
    },
    {
        id: 5,
        appName: 'Xever',
        address: '447 3rd Junction',
        bed: 3,
        bath: 3,
        price: 541,
        ImgMain: 'http://dummyimage.com/222x115.png/cc0000/ffffff',
        shortSummary:
            'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.',
        serviceCharge: 4610,
        sequrityDeposit: 4,
        flatSize: 4959,
        Img1: 'http://dummyimage.com/201x179.png/cc0000/ffffff',
        Img2: 'http://dummyimage.com/192x235.png/ff4444/ffffff',
        img3: 'http://dummyimage.com/103x160.png/dddddd/000000',
        img4: 'http://dummyimage.com/143x108.png/ff4444/ffffff',
    },
    {
        id: 6,
        appName: 'Theo',
        address: '2 Sunbrook Junction',
        bed: 5,
        bath: 2,
        price: 545,
        ImgMain: 'http://dummyimage.com/117x135.png/dddddd/000000',
        shortSummary:
            'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.',
        serviceCharge: 5514,
        sequrityDeposit: 5,
        flatSize: 2886,
        Img1: 'http://dummyimage.com/108x113.png/5fa2dd/ffffff',
        Img2: 'http://dummyimage.com/207x241.png/cc0000/ffffff',
        img3: 'http://dummyimage.com/195x117.png/dddddd/000000',
        img4: 'http://dummyimage.com/146x130.png/5fa2dd/ffffff',
    },
    {
        id: 7,
        appName: 'Rockey',
        address: '11 Kensington Place',
        bed: 5,
        bath: 3,
        price: 412,
        ImgMain: 'http://dummyimage.com/239x218.png/5fa2dd/ffffff',
        shortSummary:
            'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
        serviceCharge: 3880,
        sequrityDeposit: 2,
        flatSize: 4821,
        Img1: 'http://dummyimage.com/179x100.png/ff4444/ffffff',
        Img2: 'http://dummyimage.com/146x223.png/ff4444/ffffff',
        img3: 'http://dummyimage.com/153x109.png/ff4444/ffffff',
        img4: 'http://dummyimage.com/145x154.png/dddddd/000000',
    },
    {
        id: 8,
        appName: 'Patrizius',
        address: '5338 Brown Junction',
        bed: 4,
        bath: 3,
        price: 542,
        ImgMain: 'http://dummyimage.com/166x222.png/dddddd/000000',
        shortSummary:
            'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.',
        serviceCharge: 6044,
        sequrityDeposit: 4,
        flatSize: 4358,
        Img1: 'http://dummyimage.com/198x109.png/dddddd/000000',
        Img2: 'http://dummyimage.com/153x175.png/5fa2dd/ffffff',
        img3: 'http://dummyimage.com/132x169.png/dddddd/000000',
        img4: 'http://dummyimage.com/114x185.png/ff4444/ffffff',
    },
    {
        id: 9,
        appName: 'Fayette',
        address: '0900 Parkside Place',
        bed: 3,
        bath: 1,
        price: 447,
        ImgMain: 'http://dummyimage.com/219x129.png/ff4444/ffffff',
        shortSummary:
            'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.',
        serviceCharge: 4123,
        sequrityDeposit: 2,
        flatSize: 3316,
        Img1: 'http://dummyimage.com/159x134.png/5fa2dd/ffffff',
        Img2: 'http://dummyimage.com/139x135.png/dddddd/000000',
        img3: 'http://dummyimage.com/231x226.png/5fa2dd/ffffff',
        img4: 'http://dummyimage.com/177x153.png/ff4444/ffffff',
    },
    {
        id: 10,
        appName: 'Gothart',
        address: '87 Farwell Crossing',
        bed: 5,
        bath: 1,
        price: 632,
        ImgMain: 'http://dummyimage.com/152x117.png/ff4444/ffffff',
        shortSummary:
            'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.',
        serviceCharge: 6001,
        sequrityDeposit: 4,
        flatSize: 4767,
        Img1: 'http://dummyimage.com/130x196.png/5fa2dd/ffffff',
        Img2: 'http://dummyimage.com/202x172.png/ff4444/ffffff',
        img3: 'http://dummyimage.com/177x232.png/dddddd/000000',
        img4: 'http://dummyimage.com/116x205.png/ff4444/ffffff',
    },
    {
        id: 11,
        appName: 'Lucien',
        address: '8636 Gateway Parkway',
        bed: 3,
        bath: 2,
        price: 388,
        ImgMain: 'http://dummyimage.com/137x179.png/5fa2dd/ffffff',
        shortSummary:
            'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
        serviceCharge: 5911,
        sequrityDeposit: 3,
        flatSize: 2684,
        Img1: 'http://dummyimage.com/148x181.png/ff4444/ffffff',
        Img2: 'http://dummyimage.com/249x112.png/ff4444/ffffff',
        img3: 'http://dummyimage.com/171x207.png/dddddd/000000',
        img4: 'http://dummyimage.com/205x202.png/cc0000/ffffff',
    },
    {
        id: 12,
        appName: 'Nessy',
        address: '49034 Moland Parkway',
        bed: 5,
        bath: 2,
        price: 628,
        ImgMain: 'http://dummyimage.com/242x129.png/cc0000/ffffff',
        shortSummary:
            'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.\n\nCurabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.',
        serviceCharge: 6531,
        sequrityDeposit: 6,
        flatSize: 3470,
        Img1: 'http://dummyimage.com/216x165.png/dddddd/000000',
        Img2: 'http://dummyimage.com/238x104.png/cc0000/ffffff',
        img3: 'http://dummyimage.com/214x223.png/ff4444/ffffff',
        img4: 'http://dummyimage.com/250x146.png/dddddd/000000',
    },
];

export default FakeData;